wikipedia_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', 'placeholder-account') }}"
      user: "{{ env_var('SNOWFLAKE_USER', 'placeholder-user') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', 'placeholder-password') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'PUBLIC') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'placeholder-database') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'placeholder-warehouse') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'WIKIPEDIA') }}"
      threads: 4
      keepalives_idle: 240
      search_path: "{{ env_var('SNOWFLAKE_SCHEMA', 'WIKIPEDIA') }}" 